// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeX4GSQB2N3zMIbijaV1dgsGut3K1MkXg',
    appId: '1:443949428171:web:54abc83fe12183fc0f1a4e',
    messagingSenderId: '443949428171',
    projectId: 'go-permit',
    authDomain: 'go-permit.firebaseapp.com',
    storageBucket: 'go-permit.appspot.com',
    measurementId: 'G-ZBG7XD4N3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRVAGDatwArHKwLTpJH7W9Ww-lsLRhRvM',
    appId: '1:443949428171:android:9407f844e56917a60f1a4e',
    messagingSenderId: '443949428171',
    projectId: 'go-permit',
    storageBucket: 'go-permit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaeN-EuhZoW_E8JM4YVww0OjjL7b5ZEFg',
    appId: '1:443949428171:ios:63f3546494cba7b10f1a4e',
    messagingSenderId: '443949428171',
    projectId: 'go-permit',
    storageBucket: 'go-permit.appspot.com',
    iosClientId: '443949428171-i6k50mfjmqlc3qtp1jrgmjr46ps0rl9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.gopermit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaeN-EuhZoW_E8JM4YVww0OjjL7b5ZEFg',
    appId: '1:443949428171:ios:63f3546494cba7b10f1a4e',
    messagingSenderId: '443949428171',
    projectId: 'go-permit',
    storageBucket: 'go-permit.appspot.com',
    iosClientId: '443949428171-i6k50mfjmqlc3qtp1jrgmjr46ps0rl9p.apps.googleusercontent.com',
    iosBundleId: 'com.example.gopermit',
  );
}
